export const TEST_ACCOUNTS = [
  {
    email: 'test-admin@test.com',
    password: 'TestAdmin123!',
    name: 'Test Admin',
    role: 'admin' as const,
    label: 'Admin',
    description: 'Full admin access',
    color: 'bg-red-500',
  },
  {
    email: 'test-business@test.com',
    password: 'TestBusiness123!',
    name: 'Test Business',
    role: 'business' as const,
    label: 'Business',
    description: 'Has active business',
    color: 'bg-blue-500',
  },
  {
    email: 'test-referrer@test.com',
    password: 'TestReferrer123!',
    name: 'Test Referrer',
    role: 'referrer' as const,
    referrerStatus: 'active' as const,
    label: 'Promoter (Active)',
    description: 'Approved promoter',
    color: 'bg-green-500',
  },
  {
    email: 'test-pending@test.com',
    password: 'TestPending123!',
    name: 'Test Pending',
    role: 'referrer' as const,
    referrerStatus: 'pending' as const,
    label: 'Promoter (Pending)',
    description: 'Awaiting approval',
    color: 'bg-yellow-500',
  },
]
